### ISSUE TITLE
Missing empty lines

### ISSUE THREAD

**Issue by mwilczek-net** [ewa-krawczyk/user-data-test#9]
To maintain readability, please put one empty line under `let command = "";` and before `do {`. Will be easier for other people to find where are logic sections of code

----

Please remember about:

1. Creating new `feature/9` or `feature/missing_empty_lines` branch out of current master (first version is better - it's easier to find branch - issue relation)
2. Fixing things on new branch
3. Commit it (start commit name with `#9` - githbut will automatically bind commit with task like here: https://github.com/ewa-krawczyk/user-data-test/issues/7 )
3. Pushing new branch with fixes
4. Create Pull Request (If you name it using `#9 Missing empty lines` will be easier to find relation.
5. On task and PR (Pull Request) place all relations (on right hand side, there is list of different properties like, `assignees`, `labels`, etc.). Please assign me to review created PR, bind PR with task (sometimes it do not work automatically)
6. Please do not merge until I check codes 😄

**Comment by ewa-krawczyk** [comment]
changed
